config/routes.rb
Rails.application.routes.draw do
  root :to => 'inicio#index'
  get 'inicio/index'
  resources :reclamo_tiendas

  devise_for :usuarios
  resources :tiendas

  resources :reclas

  resources :clientes

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/recla.rb
class Recla < ActiveRecord::Base
  belongs_to :cliente
end

app/models/reclamo_tienda.rb
class ReclamoTienda < ActiveRecord::Base
  belongs_to :recla
  belongs_to :tienda
end

app/models/tienda.rb
class Tienda < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellido, :direccion, :comuna, :telefono, :correo)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/reclamo_tiendas_controller.rb
class ReclamoTiendasController < ApplicationController
  before_action :set_reclamo_tienda, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @reclamo_tiendas = ReclamoTienda.all
    respond_with(@reclamo_tiendas)
  end

  def show
    respond_with(@reclamo_tienda)
  end

  def new
    @reclamo_tienda = ReclamoTienda.new
    respond_with(@reclamo_tienda)
  end

  def edit
  end

  def create
    @reclamo_tienda = ReclamoTienda.new(reclamo_tienda_params)
    @reclamo_tienda.save
    respond_with(@reclamo_tienda)
  end

  def update
    @reclamo_tienda.update(reclamo_tienda_params)
    respond_with(@reclamo_tienda)
  end

  def destroy
    @reclamo_tienda.destroy
    respond_with(@reclamo_tienda)
  end

  private
    def set_reclamo_tienda
      @reclamo_tienda = ReclamoTienda.find(params[:id])
    end

    def reclamo_tienda_params
      params.require(:reclamo_tienda).permit(:recla_id, :tienda_id)
    end
end

app/controllers/reclas_controller.rb
class ReclasController < ApplicationController
  before_action :set_recla, only: [:show, :edit, :update, :destroy]

  # GET /reclas
  # GET /reclas.json
  def index
    @reclas = Recla.all
  end

  # GET /reclas/1
  # GET /reclas/1.json
  def show
  end

  # GET /reclas/new
  def new
    @recla = Recla.new
  end

  # GET /reclas/1/edit
  def edit
  end

  # POST /reclas
  # POST /reclas.json
  def create
    @recla = Recla.new(recla_params)

    respond_to do |format|
      if @recla.save
        format.html { redirect_to @recla, notice: 'Recla was successfully created.' }
        format.json { render :show, status: :created, location: @recla }
      else
        format.html { render :new }
        format.json { render json: @recla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reclas/1
  # PATCH/PUT /reclas/1.json
  def update
    respond_to do |format|
      if @recla.update(recla_params)
        format.html { redirect_to @recla, notice: 'Recla was successfully updated.' }
        format.json { render :show, status: :ok, location: @recla }
      else
        format.html { render :edit }
        format.json { render json: @recla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclas/1
  # DELETE /reclas/1.json
  def destroy
    @recla.destroy
    respond_to do |format|
      format.html { redirect_to reclas_url, notice: 'Recla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recla
      @recla = Recla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recla_params
      params.require(:recla).permit(:tienda, :reclam, :cliente_id)
    end
end

app/controllers/tiendas_controller.rb
class TiendasController < ApplicationController
  before_action :set_tienda, only: [:show, :edit, :update, :destroy]

  # GET /tiendas
  # GET /tiendas.json
  def index
    @tiendas = Tienda.all
  end

  # GET /tiendas/1
  # GET /tiendas/1.json
  def show
  end

  # GET /tiendas/new
  def new
    @tienda = Tienda.new
  end

  # GET /tiendas/1/edit
  def edit
  end

  # POST /tiendas
  # POST /tiendas.json
  def create
    @tienda = Tienda.new(tienda_params)

    respond_to do |format|
      if @tienda.save
        format.html { redirect_to @tienda, notice: 'Tienda was successfully created.' }
        format.json { render :show, status: :created, location: @tienda }
      else
        format.html { render :new }
        format.json { render json: @tienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiendas/1
  # PATCH/PUT /tiendas/1.json
  def update
    respond_to do |format|
      if @tienda.update(tienda_params)
        format.html { redirect_to @tienda, notice: 'Tienda was successfully updated.' }
        format.json { render :show, status: :ok, location: @tienda }
      else
        format.html { render :edit }
        format.json { render json: @tienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiendas/1
  # DELETE /tiendas/1.json
  def destroy
    @tienda.destroy
    respond_to do |format|
      format.html { redirect_to tiendas_url, notice: 'Tienda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tienda
      @tienda = Tienda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tienda_params
      params.require(:tienda).permit(:nombre, :ubicacion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/reclamo_tiendas_helper.rb
module ReclamoTiendasHelper
end

app/helpers/reclas_helper.rb
module ReclasHelper
end

app/helpers/tiendas_helper.rb
module TiendasHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Lista de Clientes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="info">Nombre</th>
      <th class="info">Apellido</th>
      <th class="info">Direccion</th>
      <th class="info">Comuna</th>
      <th class="info">Telefono</th>
      <th class="info">Correo</th>
      <th class="info" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td class="success"><%= cliente.nombre %></td>
        <td class="success"><%= cliente.apellido %></td>
        <td class="success"><%= cliente.direccion %></td>
        <td class="success"><%= cliente.comuna %></td>
        <td class="success"><%= cliente.telefono %></td>
        <td class="success"><%= cliente.correo %></td>
        <td class="success"><%= link_to 'Show', cliente %></td>
        <td class="success"><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td class="success"><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @cliente.apellido %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cliente.direccion %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @cliente.comuna %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @cliente.correo %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/inicio/index.html.erb
<h1>Inicio#index</h1>
<p>Find me in app/views/inicio/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reclamo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
  <%= render 'shared/navbar'%>
  <div class="container">
  <%= yield %>
  <p class="notice"><%=notice %></p>
  <p class="alert"><%=notice %></p>
  </div>
</body>
</html>

app/views/reclamo_tiendas/_form.html.erb
<%= form_for(@reclamo_tienda) do |f| %>
  <% if @reclamo_tienda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reclamo_tienda.errors.count, "error") %> prohibited this reclamo_tienda from being saved:</h2>

      <ul>
      <% @reclamo_tienda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recla_id %><br>
    <%= f.text_field :recla_id %>
  </div>
  <div class="field">
    <%= f.label :tienda_id %><br>
    <%= f.text_field :tienda_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reclamo_tiendas/edit.html.erb
<h1>Editing reclamo_tienda</h1>

<%= render 'form' %>

<%= link_to 'Show', @reclamo_tienda %> |
<%= link_to 'Back', reclamo_tiendas_path %>

app/views/reclamo_tiendas/index.html.erb
<h1>Resumen de Reclamo a Tiendas</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="info">Recla</th>
      <th class="info">Tienda</th>
      <th class="info" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reclamo_tiendas.each do |reclamo_tienda| %>
      <tr>
        <td class="success"><%= reclamo_tienda.recla %></td>
        <td class="success"><%= reclamo_tienda.tienda %></td>
        <td class="success"><%= link_to 'Show', reclamo_tienda %></td>
        <td class="success"><%= link_to 'Edit', edit_reclamo_tienda_path(reclamo_tienda) %></td>
        <td class="success"><%= link_to 'Destroy', reclamo_tienda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reclamo tienda', new_reclamo_tienda_path %>

app/views/reclamo_tiendas/new.html.erb
<h1>New reclamo_tienda</h1>

<%= render 'form' %>

<%= link_to 'Back', reclamo_tiendas_path %>

app/views/reclamo_tiendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recla:</strong>
  <%= @reclamo_tienda.recla %>
</p>

<p>
  <strong>Tienda:</strong>
  <%= @reclamo_tienda.tienda %>
</p>

<%= link_to 'Edit', edit_reclamo_tienda_path(@reclamo_tienda) %> |
<%= link_to 'Back', reclamo_tiendas_path %>

app/views/reclas/_form.html.erb
<%= form_for(@recla) do |f| %>
  <% if @recla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recla.errors.count, "error") %> prohibited this recla from being saved:</h2>

      <ul>
      <% @recla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tienda %><br>
    <%= f.text_field :tienda %>
  </div>
  <div class="field">
    <%= f.label :reclam %><br>
    <%= f.text_field :reclam %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br>
    <%= f.text_field :cliente_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reclas/edit.html.erb
<h1>Editing recla</h1>

<%= render 'form' %>

<%= link_to 'Show', @recla %> |
<%= link_to 'Back', reclas_path %>

app/views/reclas/index.html.erb
<h1>Lista de Reclamos</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="info">Tienda</th>
      <th class="info">Reclam</th>
      <th class="info">Cliente</th>
      <th class="info" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reclas.each do |recla| %>
      <tr>
        <td class="success"><%= recla.tienda %></td>
        <td class="success"><%= recla.reclam %></td>
        <td class="success"><%= recla.cliente %></td>
        <td class="success"><%= link_to 'Show', recla %></td>
        <td class="success"><%= link_to 'Edit', edit_recla_path(recla) %></td>
        <td class="success"><%= link_to 'Destroy', recla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recla', new_recla_path %>

app/views/reclas/new.html.erb
<h1>New recla</h1>

<%= render 'form' %>

<%= link_to 'Back', reclas_path %>

app/views/reclas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tienda:</strong>
  <%= @recla.tienda %>
</p>

<p>
  <strong>Reclam:</strong>
  <%= @recla.reclam %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @recla.cliente %>
</p>

<%= link_to 'Edit', edit_recla_path(@recla) %> |
<%= link_to 'Back', reclas_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%=clientes_path%>">Clientes</a></li>
        <li><a href="<%=reclas_path%>">Reclamos</a></li>
        <li><a href="<%=reclamo_tiendas_path%>">Tiendas-Reclamos</a></li>
        <li class="dropdown">
        </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Tiendas-Reclamos</a></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/tiendas/_form.html.erb
<%= form_for(@tienda) do |f| %>
  <% if @tienda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tienda.errors.count, "error") %> prohibited this tienda from being saved:</h2>

      <ul>
      <% @tienda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br>
    <%= f.text_field :ubicacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tiendas/edit.html.erb
<h1>Editing tienda</h1>

<%= render 'form' %>

<%= link_to 'Show', @tienda %> |
<%= link_to 'Back', tiendas_path %>

app/views/tiendas/index.html.erb
<h1>Listing tiendas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ubicacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tiendas.each do |tienda| %>
      <tr>
        <td><%= tienda.nombre %></td>
        <td><%= tienda.ubicacion %></td>
        <td><%= link_to 'Show', tienda %></td>
        <td><%= link_to 'Edit', edit_tienda_path(tienda) %></td>
        <td><%= link_to 'Destroy', tienda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tienda', new_tienda_path %>

app/views/tiendas/new.html.erb
<h1>New tienda</h1>

<%= render 'form' %>

<%= link_to 'Back', tiendas_path %>

app/views/tiendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tienda.nombre %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @tienda.ubicacion %>
</p>

<%= link_to 'Edit', edit_tienda_path(@tienda) %> |
<%= link_to 'Back', tiendas_path %>